name: Update README with Directory Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate directory structure
        run: |
          echo "# Daftar Folder dan File" > README.md
          echo "\n## Struktur Direktori\n" >> README.md
          echo '```' >> README.md
          tree -L 2 >> README.md
          echo '```' >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with directory structure'
          git push
